[package]
name = "treliudp"
version = "0.1.0"
authors = ["Cobrand <cobrandw@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reliudp = { path = "../reliudp" }
bincode = "^1"
serde = { version = "^1", features = ["derive"] }

log = "0.4"

update_regulator = { path = "../update_regulator" }